### ISSUE TITLE
wondering about how to generate the screenshot terrain as you show in the home page

### ISSUE THREAD

**Issue by niuxu18** [theSoenke/ProceduralTerrain#3]
Hello, there. I have downloaded your source code and run the VoxelDemo scene inside the scene directory. But the generated terrain has no trees or holes in mountains (like the one in the screeshot images of the home page). I wonder how should i reproduce terrain with trees or other plants ?

Thanks for your attention ~

**Comment by theSoenke** [comment]
Generating different terrain types can be achieved by changing the noise parameters e.g. increasing the amplitude.

You can add trees and other objects in the placements tab on the TerrainBuilder object:

![terrainbuilder](https://user-images.githubusercontent.com/1757301/44632736-32eb7580-a980-11e8-9b8c-b5f8abc00b92.png)

 For the grass you would need a custom terrain shader as it is not included.

**Comment by niuxu18** [comment]
thanks for your help
